INSERT INTO hotels(name, description, photo_url, price_per_night) 
VALUES 
('Costa del Sol Resort', 'Resort de lujo frente al mar con spa, tres restaurantes y actividades acuáticas', 'https://static.leonardo-hotels.com/image/leonardohotelbucharestcitycenter_room_comfortdouble2_2022_4000x2600_7e18f254bc75491965d36cc312e8111f_1200x780_mobile_3.webp', 449.99),
('Hotel Campo Verde', 'Hotel tranquilo en el campo con vistas a la montaña, ideal para escapadas románticas', 'https://static.leonardo-hotels.com/image/P_LHBLR_05_may16_4000x2600_8254e8943e796f7d44a32ffd8d650a25_1200x780_mobile_3.webp', 99.89),
('Urbano Moderno', 'Hotel boutique en el centro de la ciudad con decoración moderna y un bar en la azotea', 'https://static.leonardo-hotels.com/image/p_lrhbf_02_nov21_-4000x2600_0039400c1259e6b7fe1a79ef368294b9_1200x780_mobile_3.webp', 199.20),
('Refugio de Montaña', 'Hotel en la montaña con acceso a senderos de trekking y vistas panorámicas', 'https://www.estiber.com/blog/wp-content/uploads/2023/07/refugio-lluis-estasen.jpg', 37.99),
('Hotel La Joya de Benidorm', 'Hotel en primera linea de playa en Benidorm, con opcion a pension completa por un precio muy economico','https://media-cdn.tripadvisor.com/media/photo-s/16/1a/ea/54/hotel-presidente-4s.jpg',35),
('Hotel Trinidad',' Hotel a escasos metros de la playa de San Lorenzo en Gijon, ideal para surfistas', 'https://amenitiz.com/wp-content/uploads/2022/10/rrcibe846jo71ryoxahw.jpg',28),
('Hotel Serenidad Estelar',' Sumérgete en el lujo celestial en nuestro hotel boutique. Con habitaciones elegantes, vistas panorámicas y un servicio que supera las expectativas','https://cdn2.paraty.es/best-corporate/images/8c53b2a0997e5c1=s1900',30),
('Palacio del Ocaso', 'Experimenta la opulencia en el Palacio del Ocaso, donde la arquitectura majestuosa se encuentra con el confort moderno. Nuestras suites lujosas y servicios de clase mundial te transportarán a un mundo de indulgencia.','https://elysees-paris-hotel.com/_novaimg/4820825-1465487_0_0_2400_1536_2000_1280.jpg', 300.47),
('Royal Hideaway Corales Suites, Tenerife', 'Resort de lujo frente al mar con spa, tres restaurantes y actividades acuáticas', 'https://www.mundodeportivo.com/files/gallery_slide/uploads/2023/05/25/646f2fa76c64f.jpeg', 85.99),
('Mansiones del Tiempo', 'Viaja a través de la historia en las Mansiones del Tiempo, donde cada habitación te lleva a una época diferente. Desde la elegancia victoriana hasta la modernidad contemporánea, nuestro hotel es un viaje a través de las eras.', 'https://procoen.com/wp-content/uploads/2019/09/humedad-en-habitaciones-de-hotel.jpg', 25.54),
('Hotel Cuevas', 'Sumérgete en la serenidad celestial en el Cielo y Mar Resort, donde el lujo se encuentra con la costa. Con suites frente al mar, spa de clase mundial y gastronomía gourmet, este resort ofrece una experiencia sublime.' ,' https://www.mundodeportivo.com/files/gallery_slide/uploads/2023/05/25/646f2ff47c25f.jpeg', 28.99);